# Generated by Django 5.1.4 on 2025-01-03 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên bằng')),
                ('tuition', models.PositiveIntegerField(default=1000, verbose_name='Học phí')),
            ],
            options={
                'verbose_name': 'Loại bằng',
                'verbose_name_plural': 'Các loại bằng',
            },
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Kích hoạt')),
                ('theory_ok', models.BooleanField(default=False, verbose_name='Hoàn thành lý thuyết')),
                ('pratice_ok', models.BooleanField(default=False, verbose_name='Hoàn thành thực hành')),
                ('is_qualified', models.BooleanField(default=False, verbose_name='Đã đạt')),
                ('is_graduation', models.BooleanField(default=False, verbose_name='Đã tốt nghiệp')),
                ('tuition', models.PositiveIntegerField(blank=True, verbose_name='Học phí')),
                ('tuition_paid', models.PositiveIntegerField(blank=True, verbose_name='Học phí đã đóng')),
                ('exam_tuition', models.PositiveIntegerField(blank=True, verbose_name='Phí kiểm tra')),
                ('exam_tuition_paid', models.PositiveIntegerField(blank=True, verbose_name='Phí kiểm tra đã đóng')),
                ('exam_tuition_note', models.CharField(blank=True, max_length=50, verbose_name='Ghi chú phí kiểm tra')),
                ('a1_note', models.CharField(blank=True, max_length=50, verbose_name='Ghi chú A1')),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
                ('license_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.license', verbose_name='Bằng')),
            ],
            options={
                'verbose_name': 'Bằng lái xe',
                'verbose_name_plural': 'Bằng lái xe',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khóa học')),
                ('exam_date', models.DateField(blank=True, verbose_name='Ngày thi')),
                ('graduation_date', models.DateField(blank=True, verbose_name='Ngày tốt nghiệp')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_courses', to='course.driverlicense', verbose_name='Học viên')),
                ('license_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.license', verbose_name='Loại bằng')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Các khóa học',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên bài học')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Khóa học')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Các bài học',
            },
        ),
        migrations.CreateModel(
            name='LessonAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Hiện diện')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Bài học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.driverlicense', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm danh lý thuyết',
                'verbose_name_plural': 'Điểm danh lý thuyết',
            },
        ),
        migrations.CreateModel(
            name='PracticeAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=1, verbose_name='Thời gian')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Ngày')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.driverlicense', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Điểm danh thực hành',
                'verbose_name_plural': 'Điểm danh thực hành',
            },
        ),
    ]
