# Generated by Django 5.1.4 on 2025-01-06 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu')),
            ],
            options={
                'verbose_name': 'Mẫu khóa học',
                'verbose_name_plural': 'Các mẫu khóa học',
            },
        ),
        migrations.CreateModel(
            name='LessonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu bài học')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursetemplate', verbose_name='Mẫu khóa học')),
            ],
            options={
                'verbose_name': 'Mẫu khóa học',
                'verbose_name_plural': 'Các mẫu khóa học',
            },
        ),
    ]
