# Generated by Django 5.1.4 on 2025-01-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursetemplate_lessontemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontemplate',
            options={'verbose_name': 'Mẫu bài học', 'verbose_name_plural': 'Các mẫu bài học'},
        ),
    ]
