# Generated by Django 5.1.4 on 2025-01-06 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lessontemplate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tên bằng'),
        ),
        migrations.AddConstraint(
            model_name='driverlicense',
            constraint=models.UniqueConstraint(fields=('user', 'license_fk'), name='unique_driver_license'),
        ),
    ]
