# Generated by Django 5.1.4 on 2025-01-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_license_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lessonattend',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='unique_attend_lesson_student'),
        ),
    ]
