# Generated by Django 5.1.4 on 2025-01-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_lessonattend_unique_attend_lesson_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='exam_tuition',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Phí kiểm tra'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='exam_tuition_paid',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Phí kiểm tra đã đóng'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='tuition',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Học phí'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='tuition_paid',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Học phí đã đóng'),
        ),
    ]
