# Generated by Django 5.1.4 on 2025-01-07 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_students_driverlicense_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlicense',
            old_name='pratice_ok',
            new_name='practice_ok',
        ),
    ]
