# Generated by Django 5.1.4 on 2025-01-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_rename_pratice_ok_driverlicense_practice_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='graduation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tốt nghiệp'),
        ),
    ]
