# Generated by Django 5.1.4 on 2025-01-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_course_exam_date_alter_course_graduation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='Lớp đăng ký'),
        ),
    ]
