# Generated by Django 5.1.4 on 2025-01-06 04:23

import annoying.fields
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(blank=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phải nhập chính xác 9 hoặc 12 chữ số', regex='^(?:[0-9]{9}|[0-9]{12})$')], verbose_name='CCCD')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Địa chỉ')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, verbose_name='Giới tính')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='SĐT')),
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ người dùng',
                'verbose_name_plural': 'Các hồ sơ người dùng',
            },
        ),
    ]
