# Generated by Django 5.1.4 on 2025-01-06 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Loại báo cáo')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Loại báo cáo',
                'verbose_name_plural': 'Các loại báo cáo',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('desc', models.TextField(blank=True, verbose_name='Mô tả')),
                ('completed', models.BooleanField(default=False, verbose_name='Hoàn thành')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.reportcat', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Báo cáo',
                'verbose_name_plural': 'Các Báo cáo',
            },
        ),
    ]
